### PR TITLE
Keep the /share route from flickering

### LINKED ISSUE #6229: Flickering in the recording/…/share routing
Check out this Replay:
https://app.replay.io/recording/replay-of-a-replay--8ccec6d3-9d89-40a4-b379-efd6337ee19f?point=46406153187993451429831749081761164&time=30942&hasFrames=false#

It's technically possible to complete this task, so it's not 100% broken ... but it definitely feels like things are very wrong. From a UX/onboarding standpoint, this is high importance to fix and get right.

### PR DESCRIPTION
**Pull request by jaril**
Fix #6229 .

### CODE REVIEW

File: src/ui/hooks/recordings.ts [hunk 1]
```diff
@@ -174,6 +174,8 @@ export function useGetRecording(recordingId: RecordingId | null | undefined): {
   // Tests don't have an associated user so we just let it bypass the check here.
   const isAuthorized = isTest() || recording;
 
+  console.log(">>>>", {data, error, loading})
```
Comment (ryanjduffy) [inline src/ui/hooks/recordings.ts:177]: 🪓

**Review by ryanjduffy — APPROVED** [review]
minus the `console.log`
