### PR TITLE
Make sure that the user is flushed from the browser pref upon logout

### LINKED ISSUE #758: Replay browser continues to show the Record button even though the user has logged out
**Describe the bug**
On the Replay browser, the record button is shown even though the user has already logged out.

**To Reproduce**
1. Open the Replay browser.
2. Login.
3. Logout.
4. Notice that the record button is still displayed.

**Expected behavior**
The record button should be hidden upon user logout.

### PR DESCRIPTION
**Pull request by jaril**
Fixes #758.

We usually tell the Replay browser's prefs about the user's ID through the Avatar component. 

https://github.com/RecordReplay/devtools/blob/86a74874efcd0a739c6f1623e4467ea2cb27d7e0/src/ui/components/Avatar.js#L8-L20

The problem is that Avatar component is not rendered if the user is not logged in. So when a user logs in, logs out, then is redirected to the welcome page, the Replay browser's prefs are not updated.

This makes it so we tell the browser that the user is logged out.

### CODE REVIEW

File: src/ui/components/Account/index.js [hunk 1]
```diff
@@ -63,6 +64,10 @@ function AccountPage() {
 function WelcomePage() {
   const { loginWithRedirect } = useAuth0();
 
+  useEffect(() => {
+    setUserInBrowserPrefs("");
```
Comment (jasonLaster) [inline src/ui/components/Account/index.js:68]: `setUserInBrowserPrefs(null)`

**Review by jasonLaster — APPROVED** [review]
One tweak. otherwise great
