### PR TITLE
Remove minimist

### LINKED ISSUE #653: test and deploy action is broken
See e.g. https://github.com/RecordReplay/devtools/runs/1118916465?check_suite_focus=true

Error: Cannot find module 'minimist'

### PR DESCRIPTION
**Pull request by jaril**
Fixes #653

### CODE REVIEW

File: test/scripts/breakpoints-01.js [hunk 1]
```diff
@@ -23,5 +25,8 @@
   await resumeToLine(21);
   await checkEvaluateInTopFrame("number", 10);
 
+  dump(`>>breakpoints-01.js calling Test.finish()\n`);
+  console.log(`>>breakpoints-01.js starting log`);
```
Comment (jasonLaster) [inline test/scripts/breakpoints-01.js:29]: do you need these logs?

**Review by jasonLaster — APPROVED** [review]
one qs, otherwise good

**Comment by jaril** [comment]
When this was merged, it had two tests failing: `breakpoints-04.js` and `console_warp-01.js`

Both of these tests were passing locally and it appears that the test failures were intermittent. I've filed issues for the intermittent failures, re-ran the tests and everything is passing. 

https://github.com/RecordReplay/devtools/actions/runs/259468150
