### PR TITLE
Fix sharing modal fixes #1864

### LINKED ISSUE #1864: Open Sharing preferences is empty for accounts

### PR DESCRIPTION
**Pull request by jasonLaster**

### CODE REVIEW

File: src/ui/state/app.ts [hunk 1]
```diff
@@ -32,6 +32,7 @@ export interface AppState {
   expectedError: ExpectedError | null;
   unexpectedError: sessionError | null;
   modal: ModalType | null;
+  modalOptions: Object | null;
```
Comment (hbenl) [inline src/ui/state/app.ts:35]: Why not `modalOptions: { recordingId: RecordingId } | null;` ?

**Review by hbenl — CHANGES_REQUESTED** [review]
Please use a proper type for `modalOptions`.
