### PR TITLE
Fix the console's pausedExecution point and time

### LINKED ISSUE #1504: Console Evaluations are shown at the bottom
**Description:**
It looks like we regressed console evaluations. likely when we added some of the recent UI changes

**Steps to Reproduce:**
1. add some logpoints
2. seek to a point
3. evaluate something in the console

**Expected Result:**

result shows next to the pause line

### PR DESCRIPTION
**Pull request by jaril**
Fixes #1504.

This fixes the command+result regression from #1451.

Demo: https://share.descript.com/view/dMf4D4H8Gbk

### CODE REVIEW

File: src/devtools/client/debugger/src/actions/pause/paused.js [hunk 1]
```diff
@@ -18,9 +19,10 @@ import { setFramePositions } from "./setFramePositions";
  * @memberof actions/pause
  * @static
  */
-export function paused({ executionPoint }) {
+export function paused({ executionPoint, time }) {
   return async function ({ dispatch, getState }) {
     dispatch({ type: "PAUSED", executionPoint });
+    dispatch(actions.setPauseExecutionPoint(executionPoint, time));
```
Comment (jasonLaster) [inline src/devtools/client/debugger/src/actions/pause/paused.js:25]: could we go one step further and get rid of `setPauseExecutionPoint`?

 ```
dispatch({ type: "PAUSED", executionPoint, time });
```

and in `reducers/messages` handle the `PAUSED` action. Having fewer actions is easier to understand

**Review by jasonLaster — COMMENTED** [review]
Looks good!

This is a good opportunity to update a console test to also ensure that the message is in the right spot too.

**Review by jasonLaster — APPROVED** [review]
