### PR TITLE
fix node scroll bug in tree component

### LINKED ISSUE #1173: Sources panel jumps when toggling a node
**Describe the bug**

The sources panel sometimes jumps to the bottom when a node is toggled. This also sometimes happens in the Scopes panel too, which makes me think it's a bug in the Tree component.

**STR**

1. go to https://replay.io/view?id=02bc4c99-86b7-4a8e-b7e2-c397464f1db1
2. toggle nodes in the sources tree

Notice how the tree sometimes scrolls down to the selected node

https://www.loom.com/share/0b9a7e9a1a8f4b3198acd9a236786b64

### PR DESCRIPTION
**Pull request by karina-y**
fixes #1173 bug
we were checking if the parent of the source node was in view, now checking if the source node is in view of the tree pane

### CODE REVIEW

**Comment by karina-y** [comment]
@jasonLaster all the failed tests pass locally except breakpoints-06 again times out

File: src/devtools/client/debugger/packages/devtools-components/src/tree.js [hunk 1]
```diff
@@ -752,10 +752,10 @@ class Tree extends Component {
           }
           return closestScrolledParent(node.parentNode);
         };
-        const scrolledParent = closestScrolledParent(treeElement);
-        const scrolledParentRect = scrolledParent ? scrolledParent.getBoundingClientRect() : null;
+
+        const scrolledParentRect = treeElement ? treeElement.getBoundingClientRect() : null;
```
Comment (jasonLaster) [inline src/devtools/client/debugger/packages/devtools-components/src/tree.js:756]:
```
treeElement?.getBoundingClientRect()
```

**Review by jasonLaster — APPROVED** [review]
Feel free to land if it works on these recordings in the sources panel and scopes panel:


https://replay.io/view?id=02bc4c99-86b7-4a8e-b7e2-c397464f1db1
https://replay.io/view?id=da4faa7a-0254-4b0b-a3ff-61209009c336

**Comment by jasonLaster** [comment]
Could you update the commit message :) 

```
git commit --amend
```

**Comment by karina-y** [comment]
@jasonLaster just checked both those and they're working great!
safe to ship?
