### PR TITLE
Fix gutter clicks on space occupied by a widget

### LINKED ISSUE #996: Clicking on the area under a breakpoint re-adds the breakpoint
When we add a breakpoint, the editor's gutter is expanded to make space for the breakpoint panel. Clicking on the extra space appears resets the breakpoint's options to the default log message. I think we might be re-adding the breakpoint on that gutter click.

Before adding a breakpoint:
```
| 1|
| 2|
| 3|
| 4|
```

After adding a breakpoint:
```
| 1|
| 2| <-- Breakpoint added to line 2
|  | <-- Clicking here re-adds breakpoint to line 2
|  | <-- Clicking here re-adds breakpoint to line 2
| 3|
| 4|
```

### PR DESCRIPTION
**Pull request by jaril**
Fix #996.

### CODE REVIEW

File: src/devtools/client/debugger/src/actions/breakpoints/index.js [hunk 1]
```diff
@@ -198,6 +198,13 @@ export function addBreakpointAtLine(cx, line, shouldLog = false, disabled = fals
     if (!source) {
       return;
     }
+
+    const breakpointExists = getBreakpointAtLocation(state, { line, column: undefined });
```
Comment (jasonLaster) [inline src/devtools/client/debugger/src/actions/breakpoints/index.js:202]: this seems counterintuitive and might need a comment describing why we do it.

**Review by jasonLaster — APPROVED** [review]
