### PR TITLE
Make sure to show an error in the console when the user enables exceptions but there are too many

### LINKED ISSUE #5433: No feedback when there are too many exceptions to run an analysis
Viewing the recording below and turning on the exceptions toggle in the console shows a "There are too many points to complete this operation" in the browser devtools, but there is no feedback that the operation failed and the console stays blank.

https://app.replay.io/recording/7c05aa57-7ceb-4d40-ab05-bc435f704941

### PR DESCRIPTION
**Pull request by jaril**
Fix #5433

https://user-images.githubusercontent.com/15959269/156798320-3067bb28-499c-403f-9eeb-8b1fd5bd80f4.mov

### CODE REVIEW

File: src/protocol/logpoint.ts [hunk 1]
```diff
@@ -530,7 +531,14 @@ export async function setExceptionLogpoint(logGroupId: string) {
     onAnalysisResult: result => showLogpointsResult(logGroupId, result),
   };
 
-  await analysisManager.runAnalysis(params, handler);
+  try {
+    await analysisManager.runAnalysis(params, handler);
+  } catch (e: any) {
+    // Error.TooManyPoints
+    if (e.code === 55) {
```
Comment (abstractalgo) [inline src/protocol/logpoint.ts:538]: Move `55` to some const, to reduce the amount of magic. 🪄

**Review by abstractalgo — APPROVED** [review]
