### PR TITLE
trash icon is now only clickable when we have outputs to clear from the console, also removed some unused vars and imports from the FilterBar file

### LINKED ISSUE #1209: trash icon in console doesn't make its purpose obvious
**Describe the bug**
when you click the trash icon in the console pane sometimes it does nothing because there aren't evaluations for it to clear

**Expected behavior**
trash icon should be disabled and greyed out when there are no evaluations to clear. and a tooltip could appear on hover to state there are no evaluations to clear.

### PR DESCRIPTION
**Pull request by karina-y**
fixes #1209

### CODE REVIEW

**Comment by karina-y** [comment]
failed ci tests run locally:
console_warp-02 times out in local branch and master
object_preview-03 times out in local branch and master

File: src/devtools/client/webconsole/components/FilterBar/FilterBar.js [hunk 1]
```diff
@@ -136,11 +140,22 @@ class FilterBar extends Component {
...
+      if (message.type === MESSAGE_TYPE.COMMAND || message.type === MESSAGE_TYPE.RESULT) {
+        messagesExist = true;
+        break;
+      }
+    }
 
     return dom.button({
       className: "devtools-button devtools-clear-icon",
-      title: "Clear the Web Console output",
+      title: messagesExist ? "Clear the Web Console output" : "No outputs to clear",
```
Comment (jaril) [inline src/devtools/client/webconsole/components/FilterBar/FilterBar.js:157]: I'd make this more descriptive, like "Clear console evaluations" and "No console evaluations to clear"

File: src/devtools/client/webconsole/components/FilterBar/FilterBar.js [hunk 2]
```diff
@@ -136,11 +140,22 @@ class FilterBar extends Component {
   }
 
   renderClearButton() {
-    const { messagesClearEvaluations } = this.props;
+    const { messagesClearEvaluations, allMessagesById } = this.props;
+    let messagesExist = false;
```
Comment (jaril) [inline src/devtools/client/webconsole/components/FilterBar/FilterBar.js:144]: Small nit but let's call this `evaluationsExist` since messages refers to all messages.

**Review by jaril — APPROVED** [review]

File: src/devtools/client/webconsole/components/FilterBar/FilterBar.js (hunk 1 above)
Comment (karina-y) [reply src/devtools/client/webconsole/components/FilterBar/FilterBar.js]: fixed

File: src/devtools/client/webconsole/components/FilterBar/FilterBar.js (hunk 2 above)
Comment (karina-y) [reply src/devtools/client/webconsole/components/FilterBar/FilterBar.js]: fixed
