### PR TITLE
Expose promise state in object preview.

### LINKED ISSUE #2097: Promises are shown as invalid objects
**Description:**
 
I've seen promises come up as invalid objects pretty consistently. This was especially apparent when i was pairing with a new user and we were looking into a promises bug.

**Steps to Reproduce:**
1. view https://replay.io/view?id=8d9fa1a8-dee1-4024-ac4c-b37d7f6c55f6

The original app is here https://obwxr.csb.app/ and https://codesandbox.io/s/divine-https-obwxr?file=/src/index.js:103-123

**Replay:** https://replay.io/view?id=eac1476a-2d41-45c5-a906-ea3ce32c7f30

### PR DESCRIPTION
**Pull request by loganfsmyth**
I'm not totally clear on if this is the right way to do it, but I did this while testing out the backend changes so figured I'd post it. If there's a better way, feel free to take over.

Depends on https://github.com/RecordReplay/backend/issues/1568 and https://github.com/RecordReplay/gecko-dev/pull/324

Fixes #2097

### CODE REVIEW

**Comment by bhackett1024** [comment]
Can we update the object_preview-01.js test to exercise this?

File: src/protocol/thread/value.ts [hunk 1]
```diff
@@ -127,6 +127,14 @@ export class ValueFront {
     return [];
   }
 
+  previewPromiseState() {
+    if (this.hasPreview()) {
+      // Older recordings did not set promiseState so this could be null.
+      return this._object!.preview!.promiseState || null;
+    }
+    return null;
```
Comment (hbenl) [inline src/protocol/thread/value.ts:135]: Could be simplified to `return this._object?.preview?.promiseState || null;`

**Review by hbenl — APPROVED** [review]
LGTM

File: src/protocol/thread/value.ts (hunk 1 above)
Comment (loganfsmyth) [reply src/protocol/thread/value.ts:135]: Yeah I can change it. It's this way because I copy-pasted `previewContainerEntries` and never bothered to reformat it.
