### PR TITLE
Ensure split console is closed upon opening a replay

### LINKED ISSUE #729: [Console] The splitconsole is open when a recording is opened
**Describe the bug**
During my user interview with Janelle where she installed Replay, created a new account and created her first recording, I noticed that her first recording opened with the split console. This was unexpected. It may have been user error, but let's keep an eye on this. The same behavior appeared when I asked her to copy and navigate to the same URL in Chrome.

**To Reproduce**
1. Install and open the Replay browser
2. Create a new account
3. Create a new recording
4. Open that recording, check that the split console is not showing

**Expected behavior**
The toolbox should by default show the console.

### PR DESCRIPTION
**Pull request by jaril**
This makes sure that whenever a replay is opened, the splitconsole is toggled off.

Fix #729

### CODE REVIEW

File: src/ui/reducers/app.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ function initialAppState(): AppState {
     unexpectedError: null,
     theme: "theme-light",
     // Whether or not the developer tools toolbox is opened.
-    isToolboxOpen: prefs.isToolboxOpen,
+    isToolboxOpen: false,
```
Comment (jasonLaster) [inline src/ui/reducers/app.ts:13]: hmm, i think it is nice to use the pref here. In general, i'm a fan of persisting our UI settings

Comment (jaril) [reply src/ui/reducers/app.ts]: Gotcha!
