### PR TITLE
Network monitor follow-ups

### LINKED ISSUE #4566: Net Monitor follow up items
- [ ] reorder columns 
- [ ] remove status code treatment
- [ ] add query params
- [ ] add request metadata to the top section (see chrome devtools)
- [ ] add filtering
- [ ] add request types (parse content-type header)
- [ ] add stack trace as a separate panel section
- [ ] add console style fastforward/comment button

### PR DESCRIPTION
**Pull request by jcmorrow**
This has a whole bunch of changes to the network monitor!

### Changes

- Columns are reordered so that `name` is first
- Chill out the status codes, just plain text for you
- Add fast-forward and rewind buttons like the console has
- Add a query parameters section to request detail
- Make the request details into a table format under `General`
- Add a "document type" which is really just a parsed response content-type header with some charset data removed.

### Still to do

- Figure out stack trace stuff
- Add sort by columns
- Add reordering columns

Fixes #4566

### CODE REVIEW

File: src/ui/components/NetworkMonitor/utils.ts [hunk 1]
```diff
@@ -49,6 +53,18 @@ const name = (url: string): string =>
...
+  return Array.from(new URL(url).searchParams.entries() as [string, string][]);
+};
+const documentType = (headers: Header[]): string => {
+  return (
+    headers
+      .find(h => h.name.toLowerCase() === "content-type")
+      ?.value.split(",")[0]
+      .split(";")[0] || "unknown"
+  );
+};
```
Comment (jasonLaster) [inline src/ui/components/NetworkMonitor/utils.ts:67]: had to squint here, but looks legit.

**Review by jasonLaster — APPROVED** [review]
Everything looks reasonable to me. Especially given that it's dark.

File: src/ui/components/NetworkMonitor/utils.ts (hunk 1 above)
Comment (jcmorrow) [reply src/ui/components/NetworkMonitor/utils.ts:67]: Yeah, this is a little inscrutable. Let me write a slightly clearer version.
