### PR TITLE
Fix command palette v1 bugs

### LINKED ISSUE #4819: Command Palette V1 bugs
We have a prototype version of command palette, but this ticket is tracking its readiness for public release.

- [x] Work through the keyboard shortcuts we want to use
-  [x] [Command palette should have cursor up/cursor down support](#4803)
- [x] Support options doesn't seem to work (I'm in Safari)
- [x] Show privacy information takes me to a page that says "Application error: a client-side exception has occurred (see the browser console for more information)."
- [x] Open console should focus text field but doesn't seem to
- [x] Open outline should expand the area -- for me it stayed collapsed
- [x] Keep the current active command scrolled into view

### PR DESCRIPTION
**Pull request by jaril**
Fix #4819.

This PR does the following:
- Focuses the console terminal for the `Open Console` action.
- Fixes the `Show Sharing Options` action so it actually opens properly.
- Scrolls the currently active command into view when moving through with up/down.

### CODE REVIEW

**Review by jcmorrow — APPROVED** [review]
LGTM 👍

File: src/ui/actions/app.ts [hunk 1]
```diff
@@ -369,6 +369,8 @@ export function setLoadingPageTipIndex(index: number): SetLoadingPageTipIndexAct
 
 export function executeCommand(key: CommandKey): UIThunkAction {
   return ({ dispatch }) => {
+    const recordingId = getRecordingId();
```
Comment (jasonLaster) [inline src/ui/actions/app.ts:372]: this feels like something that should come from redux if possible

File: src/ui/actions/app.ts [hunk 2]
```diff
@@ -385,10 +387,11 @@ export function executeCommand(key: CommandKey): UIThunkAction {
     } else if (key === "open_console") {
       dispatch(setViewMode("dev"));
       dispatch(setSelectedPanel("console"));
+      window.jsterm.focus();
```
Comment (jasonLaster) [inline src/ui/actions/app.ts:390]: lol - the console needs some TLC :P

File: src/ui/components/CommandPalette/CommandButton.tsx [hunk 3]
```diff
@@ -1,24 +1,32 @@
...
   const onClick = () => {
     executeCommand(key);
   };
 
   const bgColors = active ? "bg-primaryAccent text-white" : "hover:bg-gray-200";
 
+  useEffect(() => {
+    if (active && buttonNode.current) {
+      buttonNode.current.scrollIntoView({ block: "nearest" });
+    }
```
Comment (jasonLaster) [inline src/ui/components/CommandPalette/CommandButton.tsx:21]: should we check that the button is not first visible.

**Review by jasonLaster — COMMENTED** [review]
Could you share a replay?

File: src/ui/components/CommandPalette/CommandButton.tsx (hunk 3 above)
Comment (jaril) [reply src/ui/components/CommandPalette/CommandButton.tsx:21]: Looks like `nearest` keeps it from doing anything unpleasant.

https://user-images.githubusercontent.com/15959269/147703631-a40144bc-4306-4570-8c70-6995ed051fa3.mov
