### PR TITLE
Only show one breakpoint pane when clicking on the source

### LINKED ISSUE #801: Multiple panels are shown
**Describe the bug**
I think this happens when i click the debug button in the console...

Screen Shot 2020-10-05 at 11 46 53 AM

### PR DESCRIPTION
**Pull request by jaril**
Fix #801. This makes sure that clicking on a logpoint's source from the console doesn't show multiple panes.

### CODE REVIEW

**Comment by jaril** [comment]
This was implemented this way before so that when a user clicks on a logpoint's source from the console, they're brought immediately to the debugger with the breakpoint pane open ready to edit that logpoint's message. 

Now that we persist the logpoint preview, this particular implementation only results in multiple breakpoint panes displayed.

Original patch: https://phabricator.services.mozilla.com/D35624

File: src/devtools/client/debugger/panel.js [hunk 1]
```diff
@@ -210,9 +210,6 @@ export class DebuggerPanel {
     const location = { sourceId, line, column };
 
     await this._actions.selectSource(cx, sourceId, location);
-    if (this._selectors.hasLogpoint(this._getState(), location)) {
-      this._actions.openConditionalPanel(location, true);
-    }
```
Comment (jasonLaster) [inline src/devtools/client/debugger/panel.js:215]: oh wow. sneaky

**Review by jasonLaster — APPROVED** [review]
