### PR TITLE
Fix getTimeFromPosition() clamp and add tests

### LINKED ISSUE #6748: Playhead can go past the end of the timeline
A Replay is worth a thousand words (but I left some comments anyways):
https://app.replay.io/recording/playhead-can-go-past-the-end-of-the-timeline--397dcb2e-cf68-49ea-bc8e-e85e65124795

image

### PR DESCRIPTION
**Pull request by bvaughn**
Resolves #6748

### CODE REVIEW

File: src/ui/utils/timeline.ts [hunk 1]
```diff
@@ -246,13 +246,12 @@ export function getPositionFromTime(time: number, zoomRegion: ZoomRegion) {
...
-  target: HTMLElement,
+  targetRect: { left: number; width: number },
   zoomRegion: ZoomRegion
 ): number {
-  const rect = target.getBoundingClientRect();
-  const x = pageX - rect.left;
+  const x = pageX - targetRect.left;
   const zoomRegionDuration = zoomRegion.endTime - zoomRegion.startTime;
-  const percentage = clamp(x / rect.width, 0, 100);
+  const percentage = clamp(x / targetRect.width, 0, 1);
```
Comment (bvaughn) [inline src/ui/utils/timeline.ts:254]: Oops 😬

**Review by markerikson — APPROVED** [review]
