### PR TITLE
Fix how comment pins are shown fixes #1908

### LINKED ISSUE #1908: The comment pin should go away on hover
https://replay.io/view?id=7a8063cc-671e-44ba-ac06-dd3ee4ceb53c

### PR DESCRIPTION
**Pull request by jasonLaster**
This updates a couple of things to make comment pins smoother

1. find the pin for the currently hovered pin
2. only show draft pins in the center
3. show the pin if we're hovering on the comment

### CODE REVIEW

File: src/ui/components/Comments/VideoComments/CommentsOverlay.js [hunk 1]
```diff
@@ -26,9 +18,31 @@ function CommentsOverlay({ pendingComment, canvas, recordingId, currentTime, set
...
-  const commentsAtTime = comments.filter(
-    comment => comment && comment.position && comment.time == currentTime
-  );
+  // Find the comment that matches the hoveredComment ID
+  if (hoveredComment) {
+    return comments.find(comment => comment.id == hoveredComment);
+  }
+
+  // Find the comment at the current position
+  return comments.find(comment => comment && comment.position && comment.time == currentTime);
```
Comment (jasonLaster) [inline src/ui/components/Comments/VideoComments/CommentsOverlay.js:27]: i assume that we now have one comment for point in time

File: src/ui/components/Comments/VideoComments/VideoComment.tsx [hunk 2]
```diff
@@ -18,15 +18,23 @@ function VideoComment({
   setHoveredComment,
   setActiveComment,
   hoveredComment,
+  currentTime,
+  hoverTime,
 }: PropsFromRedux) {
-  if (!canvas) {
+  if (!canvas || !comment) {
```
Comment (jasonLaster) [inline src/ui/components/Comments/VideoComments/VideoComment.tsx:24]: I'm more explicit about not rendering if there is no comment
