### PR TITLE
Gracefully handle the case where there is no selected request

### LINKED ISSUE #6510: Replay crashes when the zoom region gets too small?
Loom: https://www.loom.com/share/fc4539236ed14722bbf1cf66a48f0a7b

Replay: https://app.replay.io/recording/replay-crashes-when-zoom-region-too-small--d46e4c5b-218c-424f-bb69-08a612510ceb

### PR DESCRIPTION
**Pull request by bvaughn**
Resolves #6510

Previously we were only checking for a selected request ID but not ensuring that we could match it to a request within the loaded region. I'm really new to this code so I'm not sure if this indicates a broader unexpected issue that should be dug into further– but conceptually, it seems like a weak guard we had in place before so I hardened it a little bit.

Best viewed [without whitespace](https://github.com/RecordReplay/devtools/pull/6516/files?w=1).

### CODE REVIEW

File: src/ui/components/NetworkMonitor/index.tsx [hunk 1]
```diff
@@ -89,49 +89,51 @@ export const NetworkMonitor = ({
...
-                table={table}
-                data={data}
-                currentTime={currentTime}
-                onRowSelect={row => {
-                  trackEvent("net_monitor.select_request_row");
-                  dispatch(fetchFrames(row.point));
+      {({ table, data }: { table: any; data: RequestSummary[] }) => {
+        let selectedRequest;
+        if (selectedRequestId) {
+          selectedRequest = data.find(request => request.id === selectedRequestId);
```
Comment (bvaughn) [inline src/ui/components/NetworkMonitor/index.tsx:95]: If it's unexpected that we'd ever _not_ find a match here, I could add a `console.warn` log or something.

**Review by jcmorrow — APPROVED** [review]
