### PR TITLE
RequestDetails guard against empty "cookies" request header

### LINKED ISSUE #6447: [NetMonitor] TypeError: can't access property "trim", t[1] is undefined
Sentry Issue: [DEVTOOLS-26E](https://sentry.io/organizations/replay/issues/3203696026/?referrer=github_integration)

```
React ErrorBoundary Error: can't access property "trim", t[1] is undefined
  at Fr (./src/ui/components/NetworkMonitor/RequestDetails.tsx:111:17)
  at qr (./src/ui/components/NetworkMonitor/RequestDetails.tsx:262:24)
  at 8928/t.Z (./src/devtools/client/shared/components/splitter/SplitBox.tsx:25:37)
  at Table (./src/ui/components/NetworkMonitor/Table.tsx:26:4)
  at useMemo (./src/ui/components/NetworkMonitor/index.tsx:33:31)
...
(34 additional frame(s) were not displayed)

TypeError: can't access property "trim", t[1] is undefined
  at reduce (./src/ui/components/NetworkMonitor/RequestDetails.tsx:106:11)
  at c (./src/ui/components/NetworkMonitor/RequestDetails.tsx:105:6)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by bvaughn**
Resolves #6447

See the explanation here: https://github.com/RecordReplay/devtools/issues/6447#issuecomment-1103040617

### CODE REVIEW

File: src/ui/components/NetworkMonitor/RequestDetails.tsx [hunk 1]
```diff
@@ -77,6 +79,16 @@ function FormattedUrl({ url }: { url: string }) {
...
 const DetailTable = ({ className, details }: { className?: string; details: Detail[] }) => {
+  if (details.length === 0) {
+    return (
+      <div className={classNames(className, "flex flex-col")}>
+        <div className={classNames(styles.row, "cursor-pointer py-1 hover:bg-toolbarBackground")}>
+          No entries
+        </div>
+      </div>
+    );
+  }
```
Comment (bvaughn) [inline src/ui/components/NetworkMonitor/RequestDetails.tsx:90]: This change may be debatable but it seemed nicer to have a fallback UI.

Screen Shot 2022-04-19 at 4 15 27 PM

Screen Shot 2022-04-19 at 4 15 34 PM

File: src/ui/components/NetworkMonitor/RequestDetails.tsx [hunk 2]
```diff
@@ -99,6 +111,10 @@ export const TriangleToggle = ({ open }: { open: boolean }) => (
 );
 
 const parseCookie = (str: string): Record<string, string> => {
+  if (str.trim() === "") {
+    return {};
+  }
+
```
Comment (bvaughn) [inline src/ui/components/NetworkMonitor/RequestDetails.tsx:117]: Technically this function could still throw if it was passed a string like `";"` but I think that's a case where we'd _expect_ an error (that would be handled by a boundary).

**Review by jaril — APPROVED** [review]
