### PR TITLE
Show the timeline tooltip on transcript item hover fixes #1806

### LINKED ISSUE #1806: Comments: timestamps should appear as timeline tooltips
**Description:**

**Steps to Reproduce:**

**Expected Result:**

**Additional Context:**

* Screenshots:
* Video (Loom):
* Replay:

### PR DESCRIPTION
**Pull request by jasonLaster**
https://www.loom.com/share/3b3839e67b944dd8a4dfbc5594108a1a

### CODE REVIEW

File: src/ui/components/Comments/index.js [hunk 1]
```diff
@@ -33,9 +33,19 @@ function Comments({ recordingId, pendingComment }) {
 
   return (
     <div className="comments-container">
-      {sortedComments.map((comment, index) => (
-        <CommentMarker key={index} comment={comment} comments={sortedComments} index={index} />
-      ))}
+      {sortedComments.map((comment, index) => {
+        const isPrimaryHighlighted = hoveredPoint?.point === comment.point;
+        console.log({ isPrimaryHighlighted, p: comment.point, comment, hoveredPoint });
```
Comment (jaril) [inline src/ui/components/Comments/index.js:38]: 🧂

**Review by jaril — APPROVED** [review]
